export const categories = [
  { key: "soup", name: "Soup" },
  { key: "appetizer", name: "Appetizer" },
  { key: "platters_sizzlers", name: "Platters & Sizzlers" },
  { key: "salad", name: "Salad" },
  { key: "brunch", name: "Brunch" },
  { key: "pasta", name: "Pasta" },
  { key: "snacks", name: "Snacks" },
  { key: "rice_noodles", name: "Rice & Noodles" },
  { key: "curries", name: "Curries" },
  { key: "extras", name: "Extras" },
  { key: "desserts", name: "Desserts" }
];

export const goods = [
  { name: "Good1", category: "soup", price: "100.00", set: 1 },
  { name: "Good11", category: "soup", price: "110.00", set: 1 },
  { name: "Good12", category: "appetizer", price: "130.00", set: 1 },
  { name: "Good13", category: "appetizer", price: "140.00", set: 1 },
  { name: "Good14", category: "appetizer", price: "150.00", set: 2 },
  { name: "Good15", category: "appetizer", price: "160.00", set: 2 },
  { name: "Good16", category: "appetizer", price: "180.00", set: 1 },
  { name: "Good17", category: "appetizer", price: "170.00", set: 2 },
  { name: "Good18", category: "appetizer", price: "190.00", set: 1 },
  { name: "Good19", category: "appetizer", price: "200.00", set: 1 },
  { name: "Good10", category: "appetizer", price: "210.00", set: 2 },
  { name: "Good2", category: "appetizer", price: "220.00", set: 1 },
  { name: "Good3", category: "appetizer", price: "230.00", set: 1 },
  { name: "Good4", category: "appetizer", price: "110.00", set: 2 },
  { name: "Good5", category: "appetizer", price: "120.00", set: 1 },
  { name: "Good6", category: "appetizer", price: "130.00", set: 1 },
  { name: "Good7", category: "platters_sizzlers", price: "140.00", set: 1 },
  { name: "Good8", category: "platters_sizzlers", price: "150.00", set: 2 },
  { name: "Good9", category: "salad", price: "160.00", set: 1 },
  { name: "Good20", category: "salad", price: "170.00", set: 1 },
  { name: "Good21", category: "brunch", price: "180.00", set: 1 },
  { name: "Good22", category: "pasta", price: "190.00", set: 1 },
  { name: "Good23", category: "pasta", price: "120.00", set: 2 },
  { name: "Good24", category: "pasta", price: "130.00", set: 1 },
  { name: "Good25", category: "snacks", price: "140.00", set: 1 },
  { name: "Good26", category: "snacks", price: "150.00", set: 1 },
  { name: "Good27", category: "rice_noodles", price: "160.00", set: 1 },
  { name: "Good28", category: "rice_noodles", price: "100.00", set: 1 },
  { name: "Good29", category: "curries", price: "1700.00", set: 1 },
  { name: "Good30", category: "extras", price: "180.00", set: 1 },
  { name: "Good31", category: "desserts", price: "100.00", set: 1 }
];
